[workspace]
resolver = "3"
members = ["raritan-cli", "raritan-mpc", "raritan-rdm", "raritan-rfb", "raritan-common", "raritan-session"]
default-members = ["raritan-mpc"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
eyre = "0.6"
openssl = "0.10"
tracing = "0.1"
base64 = "0.22"
raritan-common = { path = "raritan-common" }
raritan-rdm = { path = "raritan-rdm" }
raritan-rfb = { path = "raritan-rfb" }
raritan-session = { path = "raritan-session" }
