[package]
name = "raritan-web"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
eyre.workspace = true
openssl.workspace = true
percent-encoding.workspace = true
raritan-common.workspace = true

[features]
vendored-openssl = ["openssl/vendored"]

[lints]
workspace = true
