[package]
name = "raritan-mpc"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
eyre.workspace = true
eframe.workspace = true
png = "0.18"
tracing.workspace = true
tracing-subscriber.workspace = true
raritan-rdm.workspace = true
raritan-rfb.workspace = true
raritan-session.workspace = true

[features]
vendored-openssl = ["raritan-rdm/vendored-openssl", "raritan-rfb/vendored-openssl"]

[build-dependencies]
vergen-gitcl = "10"
