[package]
name = "raritan-common"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
eyre.workspace = true
base64.workspace = true
openssl.workspace = true
quick-xml.workspace = true
rc4.workspace = true

[features]
vendored-openssl = ["openssl/vendored"]
